version: '3'

services:
  base_image:
    build:
      context: .
      dockerfile: Dockerfile.base

  flask:
    build:
      context: .
      dockerfile: flask/Dockerfile.flask
    restart: always
    ports:
      - "5000:5000"
    links:
      - mariadb
      - mongo
      - redis
      - llama_cpp_python
    volumes:
      - ./flask:/app
    depends_on:
      - mariadb
      - mongo
      - redis
      - llama_cpp_python
    env_file: 
      - .env
    command: gunicorn -w 2 -b :5000 app:app

  llama_cpp_python:
    build:
      context: .
      dockerfile: llama_cpp_python/Dockerfile.llama_cpp_python
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    restart: always
    ports:
      - "5001:8080"
    volumes:
      - ./llama_cpp_python:/app
      - ~/llm/models:/models
    ulimits:
      memlock:
        soft: -1
        hard: -1
    command: python3 -m llama_cpp.server --config_file llama_config.json

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: mariadb-example
    ports:
      - "6000:3306"

  mongo:
    image: mongo
    restart: always
    ports:
      - "6001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
    volumes:
      - ./mongo:/data/db

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - "6002:6379"
    volumes:
      - ./redis:/data